import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import WithOutLayout from "./components/WithOutLayout";
import { getUserRole } from "./lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

    // app/layout.js or pages/_app.js
    const roboto = Roboto({
      weight: ['400', '700'], // Specify desired weights, e.g., regular and bold
      subsets: ['latin'], // Specify character subsets for smaller file size
      display: 'swap', // Ensures text is visible while the font loads
    });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  const role = await getUserRole();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <WithOutLayout role={role ?? undefined}> {children}</WithOutLayout>
      </body>
    </html>
  );
}
