import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import WithOutLayout from "./components/WithOutLayout";
import { getUserRole } from "./lib/auth";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import { authOptions } from "./lib/authOptions";
import Providers from "./providers";
import { getOverview } from "./lib/api/merchant/overview";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// app/layout.js or pages/_app.js
const roboto = Roboto({
  weight: ['400', '700'], // Specify desired weights, e.g., regular and bold
  subsets: ['latin'], // Specify character subsets for smaller file size
  display: 'swap', // Ensures text is visible while the font loads
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const role = await getUserRole();
  const session = await getServerSession(authOptions);
  let balance = "100445" 
  if (role === "merchant") {
    const { data } = await getOverview();
    balance = data.balance
    console.log(data.balance);
  }


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <Providers session={session}>
          <WithOutLayout role={role ?? undefined} balance={balance}> {children}</WithOutLayout>
          <Toaster position="bottom-right" />
        </Providers>

      </body>
    </html>
  );
}
